
###GET /api/auth/nonce

GET http://localhost:3000/api/therapists/all
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJiMDRhZTc5ZC1lZTk5LTQzMTktYmU0OC1kN2EzYmE5NDgyN2YiLCJyb2xlIjoidXNlciIsIndhbGxldEFkZHJlc3MiOm51bGwsImlhdCI6MTc0OTQyNDAzOCwiZXhwIjoxNzUwMDI4ODM4fQ.8t5Hpk2OjhXDWaMyH6hz0buX37KA2_Kr3ku_KcAdAy8
### user with wallet and name

POST http://localhost:3000/api/auth/wallet
Content-Type: application/json

{
  "walletAddress":"0x1234567890abcdef1234567890abcdef12345678",
  "name":"Admin User"
}

### user with email
POST http://localhost:3000/api/auth/email
Content-Type: application/json

{"email":"admin@example.com","name":"Admin User"}

###therapists

POST http://localhost:3000/api/therapists
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIwNDJkYjUyNS1hODVhLTRlOTgtYTM2Mi1lOGMwYjVlM2I3Y2UiLCJyb2xlIjoiYWRtaW4iLCJ3YWxsZXRBZGRyZXNzIjpudWxsLCJpYXQiOjE3NDk0MTkxNzAsImV4cCI6MTc1MDAyMzk3MH0.HxPuk_BF_K4fDnxHNYRc41xdi6HRm1Mf235Yw_Dv5AQ

{
    "userId": "test126",
    "name": "Dr. Jane Doe",
    "pseudonym": "TherapistJanet2",
    "expertise": "Anxiety",
    "languages": ["English", "Spanish"],
    "verifiedHash": "0x1234567890abcdef1234567890abcdef12345673",
    "calendarUrl": "https://calendar.com/therapistjane",
    "contacts": {"supportId": "support_123"}
  }


#### journals
GET http://localhost:3000/api/journals/all
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJiMDRhZTc5ZC1lZTk5LTQzMTktYmU0OC1kN2EzYmE5NDgyN2YiLCJyb2xlIjoidXNlciIsIndhbGxldEFkZHJlc3MiOm51bGwsImlhdCI6MTc0OTQyNDAzOCwiZXhwIjoxNzUwMDI4ODM4fQ.8t5Hpk2OjhXDWaMyH6hz0buX37KA2_Kr3ku_KcAdAy8

### Create a new journal entry
POST http://localhost:3000/api/journals
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJiMDRhZTc5ZC1lZTk5LTQzMTktYmU0OC1kN2EzYmE5NDgyN2YiLCJyb2xlIjoidXNlciIsIndhbGxldEFkZHJlc3MiOm51bGwsImlhdCI6MTc0OTQyNDAzOCwiZXhwIjoxNzUwMDI4ODM4fQ.8t5Hpk2OjhXDWaMyH6hz0buX37KA2_Kr3ku_KcAdAy8

{
    "type": "text",
    "content": "Feeling stressed today.",
    "moodScore": 0.4,
    "blockchainHash": "0x1234567890abcdef1234567890abcdef12345678"
}

###Post learning
PUT http://localhost:3000/api/learning/6846243d672c8c10b5544b5b
Content-Type: application/json  
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIwNDJkYjUyNS1hODVhLTRlOTgtYTM2Mi1lOGMwYjVlM2I3Y2UiLCJyb2xlIjoiYWRtaW4iLCJ3YWxsZXRBZGRyZXNzIjpudWxsLCJpYXQiOjE3NDk0MjcxNzYsImV4cCI6MTc1MDAzMTk3Nn0.yV1mrcEZpsa4a9vwZuuVcXn8O7-wZXPMBc4JtmJ6IHo

{
    "title": "Managing Anxiety",
    "content": "# Managing Anxiety\nLearn techniques...",
    "videoUrl": "https://mockvideo.com/anxiety.mp4",
    "quiz": [
      {
        "question": "What is a common anxiety trigger?",
        "options": ["Stress", "Sleep", "Exercise", "Meditation"]
      }
    ],
    "userId": "test123"
}

### Get all learning resources
GET http://localhost:3000/api/learning/6846243d672c8c10b5544b5b
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIwNDJkYjUyNS1hODVhLTRlOTgtYTM2Mi1lOGMwYjVlM2I3Y2UiLCJyb2xlIjoiYWRtaW4iLCJ3YWxsZXRBZGRyZXNzIjpudWxsLCJpYXQiOjE3NDk0MjcxNzYsImV4cCI6MTc1MDAzMTk3Nn0.yV1mrcEZpsa4a9vwZuuVcXn8O7-wZXPMBc4JtmJ6IHo